export const mltiLanguages = (languageType) => {
  const arabic = {
    splash_desc:
      "منصة  الالكترونية تقدم مجموعة متكاملة من الخدمات التي يحتاجها العملاء في حياتهم اليومية ، وفي نفس الوقت تساعدك علي مشاركة عملك عبر الانترنت .حيث يمكنك التواصل مع الاف العملاء اون لاين في جميع انحاء الوطن العربي، ونضمن لك الحفاظ علي حقوقك وسرية البيانات بشكل كامل.",
    header: "اكتشف الآن",
    day: "دن",
    sub_header: "اكتشف مجموعاتنا الجديدة",
    section_title_tec: "أفضل الفنيين",
    sub_catrgory: "الفنيين",
    more: "شاهد المزيد",
    home: "الرئيسية",
    category: "التصنيفات",
    favorit: "المفضلة",
    chat: "الرسائل",
    profile: "الحساب",
    cart: "الحجوزات",
    notif: "الاشعارات",
    section_title_cat: "إختر ما يناسبك من الاقسام",
    section_title_pro: "أفضل الاستشاريين",
    slide_title: "إستشارات, تعليم و\n خدمات فنية",
    slide_desc:
      "العمال المدربون بمهارات خاصة ، خاصة في العلوم أو الهندسة ، ومهمتهم التأكد من عمل الآلات والمعدات بشكل صحيح ، وإصلاحها إذا لزم الأمر.",
    login_title: "تسجيل حساب",
    login_subtitle: "أدخل رقم الهاتف او البريد الالكتروني",
    email: "البريد الالكتروني",
    or: "او",
    phone: "الهاتف الجوال",
    login: "تسجيل",
    login_text: "هل تملك حساب سابق؟",
    register: "تسجيل دخول",
    name: "الاسم",
    password: "كلمة المرور",
    verif: "تأكيد رقم الهاتف",
    verif_desc: "الرجاء ادخال رمز التفعيل المرسل اليك",
    verif_text: "لم تتلقى رمز تفعيل",
    verif_btn: "إرسال مرة اخرى",
    verify: "تأكيد",
  };

  const english = {
    header: "header",
    sub_header: "sub_header",
    section_title_tec: "section_title_tec",
    more: "more",
    home: "الرئيسية",
    category: "التصنيفات",
    favorit: "المفضلة",
    chat: "الرسائل",
    profile: "الحساب",
    cart: "الحجوزات",
    notif: "الاشعارات",
    section_title_cat: "إختر ما يناسبك من الاقسام",
    section_title_pro: "أفضل الاستشاريين",
    slide_title: "إستشارات, تعليم و\n خدمات فنية",
    slide_desc:
      "العمال المدربون بمهارات خاصة ، خاصة في العلوم أو الهندسة ، ومهمتهم التأكد من عمل الآلات والمعدات بشكل صحيح ، وإصلاحها إذا لزم الأمر.",
    login_title: "تسجيل حساب",
    login_subtitle: "أدخل رقم الهاتف او البريد الالكتروني",
    email: "البريد الالكتروني",
    or: "او",
    phone: "الهاتف الجوال",
    login: "تسجيل",
    login_text: "هل تملك حساب سابق؟",
    register: "تسجيل دخول",
    name: "الاسم",
    password: "كلمة المرور",
    verif: "تأكيد رقم الهاتف",
    verif_desc: "الرجاء ادخال رمز التفعيل المرسل اليك",
    verif_text: "لم تتلقى رمز تفعيل",
    verif_btn: "إرسال مرة اخرى",
    verify: "تأكيد",
  };

  if (languageType == "eng") return english;
  if (languageType == "arabic") return arabic;
};
